version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  apt_packages:
    - default-jdk
    - graphviz
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - echo "DOT details"
      - which dot
      - export GRAPHVIZ_DOT=/usr/bin/dot
      - java -jar /home/docs/checkouts/readthedocs.org/user_builds/sphinx-needs/checkouts/rtd_jaav/docs/utils/plantuml-1.2022.14.jar -testdot
#      - ln -s /usr/bin/dot /opt/local/bin/dot
