version: 2

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - theme-furo

build:
  os: ubuntu-22.04
  apt_packages:
    - default-jdk
    - graphviz
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - echo "DOT details"
      - which dot
    pre_build:
      # ideally we would just set the DOCS_THEME environment variable
      # but I couldn't see an easy way to do that for the build job
      - 'echo "furo" > docs/DOCS_THEME'
