from pathlib import Path

import pytest


@pytest.mark.parametrize("test_app", [{"buildername": "latex", "srcdir": "doc_test/doc_build_latex"}], indirect=True)
def test_doc_build_latex(test_app):
    app = test_app

    app.build()

    latex_file = Path(app.outdir, "needstestdocs.tex")
    assert latex_file

    latex_content = latex_file.read_text()

    # Check table generated by Sphinxneeds has correct caption
    assert (
        "\\sphinxcaption{Table from sphinxneeds\\sphinxhyphen{}contrib \\textquotesingle"
        "{}needtable\\textquotesingle{} directive}" in latex_content
    )

    # Check that the USER_STORY_001 label is only created once in the LaTeX output.  Split
    # on the string, which should split latex_content into two.
    assert len(latex_content.split(r"\label{\detokenize{index:USER_STORY_001}}")) == 2
