from pathlib import Path

import pytest


@pytest.mark.parametrize("create_app", [{"buildername": "latex", "srcdir": "doc_test/doc_build_latex"}], indirect=True)
def test_doc_build_latex(create_app):
    app = create_app

    app.build()

    latex_file = Path(app.outdir, "needstestdocs.tex")
    assert latex_file

    latex_content = latex_file.read_text()

    # Check table generated by Sphinxneeds has correct caption
    assert (
        "\\sphinxcaption{Table from sphinxneeds\\sphinxhyphen{}contrib \\textquotesingle"
        "{}needtable\\textquotesingle{} directive}" in latex_content
    )
