# To use tox, see https://tox.readthedocs.io
# Simply pip or conda install tox
# then run `tox` or `tox -- {pytest args}`
# To run in parallel using `tox -p`

# To rebuild the tox environment, for example when dependencies change, use
# `tox -r`

[tox]
envlist =
    py39-sphinx{5,6,7}
    py310-sphinx{5,6,7,8}
    py311-sphinx{5,6,7,8,9}
    py312-sphinx{5,6,7,8,9}
    py313-sphinx{6,7,8,9}
    py314-sphinx{6,7,8,9}

[testenv]
usedevelop = true

[testenv:py{39,310,311,312,313,314}-sphinx{5,6,7,8,9}]
deps =
    sphinx5: sphinx>=5.0,<6
    sphinx6: sphinx>=6.0,<7
    sphinx7: sphinx>=7.0,<8
    sphinx8: sphinx>=8.0,<9
    sphinx9: sphinx>=9.0,<10
dependency_groups = testing
commands = pytest {posargs}
